[project]
name = "ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.0.0",
    "matplotlib>=3.4.0",
    "notebook>=6.4.0",
    "numpy>=1.21.0",
    "scikit-learn>=1.0.0",
    "seaborn>=0.11.0",
]
